name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install ARM toolchain
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '10-2020-q4'
    
    - name: Build QEMU simulation target
      run: make -C src/c/ dmacu_qemu_versatilepb.elf

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dmacu-qemu
        path: src/c/dmacu_qemu_versatilepb.elf
