name: "Open-CMSIS-Pack: Build DMACU demo hardware ports (LPC1769, LPC84x)"

on:
  workflow_dispatch:
  push:
    branches: [main,multiarch]
    paths:
      - src/**
      - dmacu.csolution.yml
      - .github/workflows/open-cmsis.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [AC6]
        build_type: [Debug, Release]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: Checkout repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install tools
        uses: ARM-software/cmsis-actions/vcpkg@75fd924d583d17eacdbfaf77f21ca09e335c3c79 # v1
        with:
          config: "vcpkg-configuration.json"

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@75fd924d583d17eacdbfaf77f21ca09e335c3c79 # v1

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Build DMACU demo hardware ports with ${{ matrix.toolchain }}
        working-directory: .
        run: |
          echo "Building with toolchain: ${{ matrix.toolchain }}"
          cbuild dmacu.csolution.yml --packs --toolchain ${{ matrix.toolchain }}
